---
- name: Check for supported operating system on target
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: ( ansible_os_family != "Debian" ) and
        ( ansible_os_family != "RedHat" )


- name: Extract the Version from Download URL
  command: "echo {{ go_inst.src_file_url | basename | regex_replace('^go(.*).linux-amd64.tar.gz$', '\\1') }}"
  register: version
  changed_when: false


- name: Print Version
  debug:
   msg="Got Version from URL {{ version.stdout }}"


- name: Include distro specific tasks
  include: "{{ ansible_os_family }}.yml"
