---
# https://github.com/ansible/ansible/issues/2769
- name: print download URL
  debug: >
    msg="Download URL: {{ go_inst.src_file_url }}"


- name: create /usr/local/src/go directory
  file:
   path=/usr/local/src/go/
   state=directory
   owner=root
   group=root
   mode=0755


- name: download Go src file
  get_url:
   url={{ go_inst.src_file_url }}
   dest=/usr/local/src/go/{{ go_inst.src_file_url | basename }}
   sha256sum={{ go_inst.src_file_sha256 }}
  register: go_src_file


- block:
  - name: clean old version
    file:
     path=/usr/local/go
     state=absent


  - name: extract the src Go file
    unarchive:
     src=/usr/local/src/go/{{ go_inst.src_file_url | basename }}
     dest=/usr/local
     copy=no

  when: go_src_file is changed


- name: add /usr/local/go/bin to the PATH system wide
  lineinfile:
   dest=/etc/profile
   line="export PATH=$PATH:/usr/local/go/bin"
